name: Scheduled build
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  release:
    runs-on: ubuntu-latest
    environment: base
    env:
      STORAGE_URL: ${{ secrets.STORAGE_URL }}
    steps:
      - name: SetBuildEnv
        run: echo ${{ env.STORAGE_URL }}
      - name: Clone project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: clean npm cache
        run: npm cache clean -f
      - name: install dependencies
        run: npm ci
      - name: compile
        run: bash build.sh
      - name: Commit build
        run: |
          git commit -am "autobuild"
          git push
          git tag 2023.11.11
          git push origin 2023.11.11
