name: Release

on:
  push:
    tags:
      - "**"

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      STORAGE_URL: ${{ secrets.STORAGE_URL }}
    steps:
      - name: Clone project
        uses: actions/checkout@v2
      - name: Package and release
        uses: BigWigsMods/packager@v2
