name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      STORAGE_PATH: ${{ secrets.STORAGE_PATH }}
    steps:
      - name: SetBuildEnv
        run: echo "STORAGE_PATH=$STORAGE_PATH" > .env
      - name: Clone project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: clean npm cache
        run: npm cache clean -f
      - name: install dependencies
        run: npm ci
      - name: compile
        run: bash build.sh
      - name: Package and release
        uses: BigWigsMods/packager@v2
